// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOrganisation(args: GetOrganisationArgs, opts?: pulumi.InvokeOptions): Promise<GetOrganisationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("flagsmith:index/getOrganisation:getOrganisation", {
        "uuid": args.uuid,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOrganisation.
 */
export interface GetOrganisationArgs {
    uuid: string;
}

/**
 * A collection of values returned by getOrganisation.
 */
export interface GetOrganisationResult {
    readonly force2fa: boolean;
    readonly id: number;
    readonly name: string;
    readonly persistTraitData: boolean;
    readonly restrictProjectCreateToAdmin: boolean;
    readonly uuid: string;
}
export function getOrganisationOutput(args: GetOrganisationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOrganisationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("flagsmith:index/getOrganisation:getOrganisation", {
        "uuid": args.uuid,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOrganisation.
 */
export interface GetOrganisationOutputArgs {
    uuid: pulumi.Input<string>;
}
