// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MvFeatureOption extends pulumi.CustomResource {
    /**
     * Get an existing MvFeatureOption resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MvFeatureOptionState, opts?: pulumi.CustomResourceOptions): MvFeatureOption {
        return new MvFeatureOption(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flagsmith:index/mvFeatureOption:MvFeatureOption';

    /**
     * Returns true if the given object is an instance of MvFeatureOption.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MvFeatureOption {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MvFeatureOption.__pulumiType;
    }

    /**
     * Boolean value of the multivariate option if the type is <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    declare public readonly booleanValue: pulumi.Output<boolean | undefined>;
    /**
     * Percentage allocation of the current multivariate option
     */
    declare public readonly defaultPercentageAllocation: pulumi.Output<number>;
    /**
     * ID of the feature to which the multivariate option belongs
     */
    declare public /*out*/ readonly featureId: pulumi.Output<number>;
    /**
     * UUID of the feature to which the multivariate option belongs
     */
    declare public readonly featureUuid: pulumi.Output<string>;
    /**
     * Integer value of the multivariate option if the type is <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span>
     */
    declare public readonly integerValue: pulumi.Output<number | undefined>;
    /**
     * ID of the multivariate option
     */
    declare public /*out*/ readonly mvFeatureOptionId: pulumi.Output<number>;
    /**
     * Project ID of the feature to which the multivariate option belongs
     */
    declare public /*out*/ readonly projectId: pulumi.Output<number>;
    /**
     * String value of the multivariate option if the type is <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>
     */
    declare public readonly stringValue: pulumi.Output<string | undefined>;
    /**
     * Type of the multivariate option can be <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>, <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span> or <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * UUID of the multivariate option
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a MvFeatureOption resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MvFeatureOptionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MvFeatureOptionArgs | MvFeatureOptionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MvFeatureOptionState | undefined;
            resourceInputs["booleanValue"] = state?.booleanValue;
            resourceInputs["defaultPercentageAllocation"] = state?.defaultPercentageAllocation;
            resourceInputs["featureId"] = state?.featureId;
            resourceInputs["featureUuid"] = state?.featureUuid;
            resourceInputs["integerValue"] = state?.integerValue;
            resourceInputs["mvFeatureOptionId"] = state?.mvFeatureOptionId;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["stringValue"] = state?.stringValue;
            resourceInputs["type"] = state?.type;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as MvFeatureOptionArgs | undefined;
            if (args?.defaultPercentageAllocation === undefined && !opts.urn) {
                throw new Error("Missing required property 'defaultPercentageAllocation'");
            }
            if (args?.featureUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'featureUuid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["booleanValue"] = args?.booleanValue;
            resourceInputs["defaultPercentageAllocation"] = args?.defaultPercentageAllocation;
            resourceInputs["featureUuid"] = args?.featureUuid;
            resourceInputs["integerValue"] = args?.integerValue;
            resourceInputs["stringValue"] = args?.stringValue;
            resourceInputs["type"] = args?.type;
            resourceInputs["featureId"] = undefined /*out*/;
            resourceInputs["mvFeatureOptionId"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MvFeatureOption.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering MvFeatureOption resources.
 */
export interface MvFeatureOptionState {
    /**
     * Boolean value of the multivariate option if the type is <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    booleanValue?: pulumi.Input<boolean | undefined>;
    /**
     * Percentage allocation of the current multivariate option
     */
    defaultPercentageAllocation?: pulumi.Input<number | undefined>;
    /**
     * ID of the feature to which the multivariate option belongs
     */
    featureId?: pulumi.Input<number | undefined>;
    /**
     * UUID of the feature to which the multivariate option belongs
     */
    featureUuid?: pulumi.Input<string | undefined>;
    /**
     * Integer value of the multivariate option if the type is <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span>
     */
    integerValue?: pulumi.Input<number | undefined>;
    /**
     * ID of the multivariate option
     */
    mvFeatureOptionId?: pulumi.Input<number | undefined>;
    /**
     * Project ID of the feature to which the multivariate option belongs
     */
    projectId?: pulumi.Input<number | undefined>;
    /**
     * String value of the multivariate option if the type is <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>
     */
    stringValue?: pulumi.Input<string | undefined>;
    /**
     * Type of the multivariate option can be <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>, <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span> or <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * UUID of the multivariate option
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a MvFeatureOption resource.
 */
export interface MvFeatureOptionArgs {
    /**
     * Boolean value of the multivariate option if the type is <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    booleanValue?: pulumi.Input<boolean | undefined>;
    /**
     * Percentage allocation of the current multivariate option
     */
    defaultPercentageAllocation: pulumi.Input<number>;
    /**
     * UUID of the feature to which the multivariate option belongs
     */
    featureUuid: pulumi.Input<string>;
    /**
     * Integer value of the multivariate option if the type is <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span>
     */
    integerValue?: pulumi.Input<number | undefined>;
    /**
     * String value of the multivariate option if the type is <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>
     */
    stringValue?: pulumi.Input<string | undefined>;
    /**
     * Type of the multivariate option can be <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>, <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span> or <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    type: pulumi.Input<string>;
}
