// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flagsmith:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Enable this to trigger a realtime(sse) event whenever the value of a flag changes
     */
    declare public readonly enableRealtimeUpdates: pulumi.Output<boolean>;
    /**
     * If true, feature creation requires at least one owner or group owner.
     */
    declare public readonly enforceFeatureOwners: pulumi.Output<boolean>;
    /**
     * Used for validating feature names
     */
    declare public readonly featureNameRegex: pulumi.Output<string>;
    /**
     * If true will exclude flags from SDK which are disabled
     */
    declare public readonly hideDisabledFlags: pulumi.Output<boolean>;
    /**
     * Name of the project
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Used by UI to validate feature names
     */
    declare public readonly onlyAllowLowerCaseFeatureNames: pulumi.Output<boolean>;
    /**
     * ID of the organisation project belongs to
     */
    declare public readonly organisationId: pulumi.Output<number>;
    /**
     * Prevent defaults from being set in all environments when creating a feature.
     */
    declare public readonly preventFlagDefaults: pulumi.Output<boolean>;
    /**
     * ID of the project
     */
    declare public /*out*/ readonly projectId: pulumi.Output<number>;
    /**
     * Number of days without modification in any environment before a flag is considered stale.
     */
    declare public readonly staleFlagsLimitDays: pulumi.Output<number>;
    /**
     * UUID of the project
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["enableRealtimeUpdates"] = state?.enableRealtimeUpdates;
            resourceInputs["enforceFeatureOwners"] = state?.enforceFeatureOwners;
            resourceInputs["featureNameRegex"] = state?.featureNameRegex;
            resourceInputs["hideDisabledFlags"] = state?.hideDisabledFlags;
            resourceInputs["name"] = state?.name;
            resourceInputs["onlyAllowLowerCaseFeatureNames"] = state?.onlyAllowLowerCaseFeatureNames;
            resourceInputs["organisationId"] = state?.organisationId;
            resourceInputs["preventFlagDefaults"] = state?.preventFlagDefaults;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["staleFlagsLimitDays"] = state?.staleFlagsLimitDays;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            if (args?.organisationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organisationId'");
            }
            resourceInputs["enableRealtimeUpdates"] = args?.enableRealtimeUpdates;
            resourceInputs["enforceFeatureOwners"] = args?.enforceFeatureOwners;
            resourceInputs["featureNameRegex"] = args?.featureNameRegex;
            resourceInputs["hideDisabledFlags"] = args?.hideDisabledFlags;
            resourceInputs["name"] = args?.name;
            resourceInputs["onlyAllowLowerCaseFeatureNames"] = args?.onlyAllowLowerCaseFeatureNames;
            resourceInputs["organisationId"] = args?.organisationId;
            resourceInputs["preventFlagDefaults"] = args?.preventFlagDefaults;
            resourceInputs["staleFlagsLimitDays"] = args?.staleFlagsLimitDays;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * Enable this to trigger a realtime(sse) event whenever the value of a flag changes
     */
    enableRealtimeUpdates?: pulumi.Input<boolean | undefined>;
    /**
     * If true, feature creation requires at least one owner or group owner.
     */
    enforceFeatureOwners?: pulumi.Input<boolean | undefined>;
    /**
     * Used for validating feature names
     */
    featureNameRegex?: pulumi.Input<string | undefined>;
    /**
     * If true will exclude flags from SDK which are disabled
     */
    hideDisabledFlags?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Used by UI to validate feature names
     */
    onlyAllowLowerCaseFeatureNames?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the organisation project belongs to
     */
    organisationId?: pulumi.Input<number | undefined>;
    /**
     * Prevent defaults from being set in all environments when creating a feature.
     */
    preventFlagDefaults?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the project
     */
    projectId?: pulumi.Input<number | undefined>;
    /**
     * Number of days without modification in any environment before a flag is considered stale.
     */
    staleFlagsLimitDays?: pulumi.Input<number | undefined>;
    /**
     * UUID of the project
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Enable this to trigger a realtime(sse) event whenever the value of a flag changes
     */
    enableRealtimeUpdates?: pulumi.Input<boolean | undefined>;
    /**
     * If true, feature creation requires at least one owner or group owner.
     */
    enforceFeatureOwners?: pulumi.Input<boolean | undefined>;
    /**
     * Used for validating feature names
     */
    featureNameRegex?: pulumi.Input<string | undefined>;
    /**
     * If true will exclude flags from SDK which are disabled
     */
    hideDisabledFlags?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Used by UI to validate feature names
     */
    onlyAllowLowerCaseFeatureNames?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the organisation project belongs to
     */
    organisationId: pulumi.Input<number>;
    /**
     * Prevent defaults from being set in all environments when creating a feature.
     */
    preventFlagDefaults?: pulumi.Input<boolean | undefined>;
    /**
     * Number of days without modification in any environment before a flag is considered stale.
     */
    staleFlagsLimitDays?: pulumi.Input<number | undefined>;
}
