// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Segment extends pulumi.CustomResource {
    /**
     * Get an existing Segment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SegmentState, opts?: pulumi.CustomResourceOptions): Segment {
        return new Segment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flagsmith:index/segment:Segment';

    /**
     * Returns true if the given object is an instance of Segment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Segment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Segment.__pulumiType;
    }

    /**
     * Description of the segment
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Set this to create a feature specific segment
     */
    declare public readonly featureId: pulumi.Output<number>;
    /**
     * Name of the segment
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * ID of the project
     */
    declare public /*out*/ readonly projectId: pulumi.Output<number>;
    /**
     * UUID of project the segment belongs to
     */
    declare public readonly projectUuid: pulumi.Output<string>;
    /**
     * Rules for the segment
     */
    declare public readonly rules: pulumi.Output<outputs.SegmentRule[]>;
    /**
     * ID of the segment
     */
    declare public /*out*/ readonly segmentId: pulumi.Output<number>;
    /**
     * UUID of the segment
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Segment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SegmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SegmentArgs | SegmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SegmentState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["featureId"] = state?.featureId;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["projectUuid"] = state?.projectUuid;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["segmentId"] = state?.segmentId;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as SegmentArgs | undefined;
            if (args?.projectUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectUuid'");
            }
            if (args?.rules === undefined && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["featureId"] = args?.featureId;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectUuid"] = args?.projectUuid;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["segmentId"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Segment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Segment resources.
 */
export interface SegmentState {
    /**
     * Description of the segment
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Set this to create a feature specific segment
     */
    featureId?: pulumi.Input<number | undefined>;
    /**
     * Name of the segment
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the project
     */
    projectId?: pulumi.Input<number | undefined>;
    /**
     * UUID of project the segment belongs to
     */
    projectUuid?: pulumi.Input<string | undefined>;
    /**
     * Rules for the segment
     */
    rules?: pulumi.Input<pulumi.Input<inputs.SegmentRule>[] | undefined>;
    /**
     * ID of the segment
     */
    segmentId?: pulumi.Input<number | undefined>;
    /**
     * UUID of the segment
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Segment resource.
 */
export interface SegmentArgs {
    /**
     * Description of the segment
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Set this to create a feature specific segment
     */
    featureId?: pulumi.Input<number | undefined>;
    /**
     * Name of the segment
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * UUID of project the segment belongs to
     */
    projectUuid: pulumi.Input<string>;
    /**
     * Rules for the segment
     */
    rules: pulumi.Input<pulumi.Input<inputs.SegmentRule>[]>;
}
