// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Tag extends pulumi.CustomResource {
    /**
     * Get an existing Tag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TagState, opts?: pulumi.CustomResourceOptions): Tag {
        return new Tag(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flagsmith:index/tag:Tag';

    /**
     * Returns true if the given object is an instance of Tag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Tag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Tag.__pulumiType;
    }

    /**
     * Description of the feature
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * ID of the project
     */
    declare public /*out*/ readonly projectId: pulumi.Output<number>;
    /**
     * UUID of project the tag belongs to
     */
    declare public readonly projectUuid: pulumi.Output<string>;
    /**
     * Colour for this tag, as accepted by [color-string](https://github.com/Qix-/color-string).
     */
    declare public readonly tagColour: pulumi.Output<string>;
    /**
     * ID of the tag
     */
    declare public /*out*/ readonly tagId: pulumi.Output<number>;
    /**
     * Name of the tag
     */
    declare public readonly tagName: pulumi.Output<string>;
    /**
     * UUID of the tag
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Tag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TagArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TagArgs | TagState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TagState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["projectUuid"] = state?.projectUuid;
            resourceInputs["tagColour"] = state?.tagColour;
            resourceInputs["tagId"] = state?.tagId;
            resourceInputs["tagName"] = state?.tagName;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as TagArgs | undefined;
            if (args?.projectUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectUuid'");
            }
            if (args?.tagName === undefined && !opts.urn) {
                throw new Error("Missing required property 'tagName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["projectUuid"] = args?.projectUuid;
            resourceInputs["tagColour"] = args?.tagColour;
            resourceInputs["tagName"] = args?.tagName;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["tagId"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Tag.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Tag resources.
 */
export interface TagState {
    /**
     * Description of the feature
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * ID of the project
     */
    projectId?: pulumi.Input<number | undefined>;
    /**
     * UUID of project the tag belongs to
     */
    projectUuid?: pulumi.Input<string | undefined>;
    /**
     * Colour for this tag, as accepted by [color-string](https://github.com/Qix-/color-string).
     */
    tagColour?: pulumi.Input<string | undefined>;
    /**
     * ID of the tag
     */
    tagId?: pulumi.Input<number | undefined>;
    /**
     * Name of the tag
     */
    tagName?: pulumi.Input<string | undefined>;
    /**
     * UUID of the tag
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Tag resource.
 */
export interface TagArgs {
    /**
     * Description of the feature
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * UUID of project the tag belongs to
     */
    projectUuid: pulumi.Input<string>;
    /**
     * Colour for this tag, as accepted by [color-string](https://github.com/Qix-/color-string).
     */
    tagColour?: pulumi.Input<string | undefined>;
    /**
     * Name of the tag
     */
    tagName: pulumi.Input<string>;
}
