// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface FeatureStateFeatureStateValue {
    /**
     * Boolean value of the feature if the type is <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    booleanValue?: boolean;
    /**
     * Integer value of the feature if the type is <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span>
     */
    integerValue?: number;
    /**
     * String value of the feature if the type is <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>.
     */
    stringValue?: string;
    /**
     * Type of the feature state value, can be <span pulumi-lang-nodejs="`unicode`" pulumi-lang-dotnet="`Unicode`" pulumi-lang-go="`unicode`" pulumi-lang-python="`unicode`" pulumi-lang-yaml="`unicode`" pulumi-lang-java="`unicode`" pulumi-lang-hcl="`unicode`">`unicode`</span>, <span pulumi-lang-nodejs="`int`" pulumi-lang-dotnet="`Int`" pulumi-lang-go="`int`" pulumi-lang-python="`int`" pulumi-lang-yaml="`int`" pulumi-lang-java="`int`" pulumi-lang-hcl="`int`">`int`</span> or <span pulumi-lang-nodejs="`bool`" pulumi-lang-dotnet="`Bool`" pulumi-lang-go="`bool`" pulumi-lang-python="`bool`" pulumi-lang-yaml="`bool`" pulumi-lang-java="`bool`" pulumi-lang-hcl="`bool`">`bool`</span>
     */
    type: string;
}

export interface SegmentRule {
    /**
     * List of Conditions for the nested Rule
     */
    conditions?: outputs.SegmentRuleCondition[];
    /**
     * List of Nested Rules
     */
    rules?: outputs.SegmentRuleRule[];
    /**
     * Type of the rule, can be of: `ALL`, `ANY`, `NONE`
     */
    type: string;
}

export interface SegmentRuleCondition {
    /**
     * Operator of the condition, can be one of `EQUAL`, `GREATER_THAN`, `LESS_THAN`, `LESS_THAN_INCLUSIVE` `CONTAINS`, `GREATER_THAN_INCLUSIVE`, `NOT_CONTAINS`, `NOT_EQUAL`,  `REGEX`, `PERCENTAGE_SPLIT`,  `MODULO`, `IS_SET`, `IS_NOT_SET`, `IN`
     */
    operator: string;
    /**
     * Property of the condition
     */
    property?: string;
    /**
     * Value of the condition
     */
    value?: string;
}

export interface SegmentRuleRule {
    /**
     * List of Conditions for the nested Rule
     */
    conditions?: outputs.SegmentRuleRuleCondition[];
    /**
     * Type of the rule
     */
    type: string;
}

export interface SegmentRuleRuleCondition {
    /**
     * Operator of the condition, can be one of `EQUAL`, `GREATER_THAN`, `LESS_THAN`, `LESS_THAN_INCLUSIVE` `CONTAINS`, `GREATER_THAN_INCLUSIVE`, `NOT_CONTAINS`, `NOT_EQUAL`,  `REGEX`, `PERCENTAGE_SPLIT`,  `MODULO`, `IS_SET`, `IS_NOT_SET`, `IN`
     */
    operator: string;
    /**
     * Property of the condition
     */
    property?: string;
    /**
     * Value of the condition
     */
    value?: string;
}

