// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("flagsmith");

/**
 * Used by api client to connect to flagsmith instance. NOTE: update this if you are running a self hosted version. e.g: https://your.flagsmith.com/api/v1
 */
export declare const baseApiUrl: string | undefined;
Object.defineProperty(exports, "baseApiUrl", {
    get() {
        return __config.get("baseApiUrl");
    },
    enumerable: true,
});

/**
 * Master API key used by flagsmith api client. Can also be set using the environment variable `FLAGSMITH_MASTER_API_KEY`
 */
export declare const masterApiKey: string | undefined;
Object.defineProperty(exports, "masterApiKey", {
    get() {
        return __config.get("masterApiKey");
    },
    enumerable: true,
});

